from setuptools import setup

setup(
    name='djangogirls',
    version='',
    packages=['blog', 'blog.migrations', 'mysite', 'myvenv.Lib.site-packages.pip',
              'myvenv.Lib.site-packages.pip._vendor', 'myvenv.Lib.site-packages.pip._vendor.idna',
              'myvenv.Lib.site-packages.pip._vendor.pep517', 'myvenv.Lib.site-packages.pip._vendor.pytoml',
              'myvenv.Lib.site-packages.pip._vendor.certifi', 'myvenv.Lib.site-packages.pip._vendor.chardet',
              'myvenv.Lib.site-packages.pip._vendor.chardet.cli', 'myvenv.Lib.site-packages.pip._vendor.distlib',
              'myvenv.Lib.site-packages.pip._vendor.distlib._backport', 'myvenv.Lib.site-packages.pip._vendor.msgpack',
              'myvenv.Lib.site-packages.pip._vendor.urllib3', 'myvenv.Lib.site-packages.pip._vendor.urllib3.util',
              'myvenv.Lib.site-packages.pip._vendor.urllib3.contrib',
              'myvenv.Lib.site-packages.pip._vendor.urllib3.contrib._securetransport',
              'myvenv.Lib.site-packages.pip._vendor.urllib3.packages',
              'myvenv.Lib.site-packages.pip._vendor.urllib3.packages.rfc3986',
              'myvenv.Lib.site-packages.pip._vendor.urllib3.packages.backports',
              'myvenv.Lib.site-packages.pip._vendor.urllib3.packages.ssl_match_hostname',
              'myvenv.Lib.site-packages.pip._vendor.colorama', 'myvenv.Lib.site-packages.pip._vendor.html5lib',
              'myvenv.Lib.site-packages.pip._vendor.html5lib._trie',
              'myvenv.Lib.site-packages.pip._vendor.html5lib.filters',
              'myvenv.Lib.site-packages.pip._vendor.html5lib.treewalkers',
              'myvenv.Lib.site-packages.pip._vendor.html5lib.treeadapters',
              'myvenv.Lib.site-packages.pip._vendor.html5lib.treebuilders',
              'myvenv.Lib.site-packages.pip._vendor.lockfile', 'myvenv.Lib.site-packages.pip._vendor.progress',
              'myvenv.Lib.site-packages.pip._vendor.requests', 'myvenv.Lib.site-packages.pip._vendor.packaging',
              'myvenv.Lib.site-packages.pip._vendor.cachecontrol',
              'myvenv.Lib.site-packages.pip._vendor.cachecontrol.caches',
              'myvenv.Lib.site-packages.pip._vendor.webencodings', 'myvenv.Lib.site-packages.pip._vendor.pkg_resources',
              'myvenv.Lib.site-packages.pip._internal', 'myvenv.Lib.site-packages.pip._internal.cli',
              'myvenv.Lib.site-packages.pip._internal.req', 'myvenv.Lib.site-packages.pip._internal.vcs',
              'myvenv.Lib.site-packages.pip._internal.utils', 'myvenv.Lib.site-packages.pip._internal.models',
              'myvenv.Lib.site-packages.pip._internal.commands', 'myvenv.Lib.site-packages.pip._internal.operations',
              'myvenv.Lib.site-packages.pip._internal.distributions', 'myvenv.Lib.site-packages.pytz',
              'myvenv.Lib.site-packages.django', 'myvenv.Lib.site-packages.django.db',
              'myvenv.Lib.site-packages.django.db.models', 'myvenv.Lib.site-packages.django.db.models.sql',
              'myvenv.Lib.site-packages.django.db.models.fields', 'myvenv.Lib.site-packages.django.db.models.functions',
              'myvenv.Lib.site-packages.django.db.backends', 'myvenv.Lib.site-packages.django.db.backends.base',
              'myvenv.Lib.site-packages.django.db.backends.dummy', 'myvenv.Lib.site-packages.django.db.backends.mysql',
              'myvenv.Lib.site-packages.django.db.backends.oracle',
              'myvenv.Lib.site-packages.django.db.backends.sqlite3',
              'myvenv.Lib.site-packages.django.db.backends.postgresql',
              'myvenv.Lib.site-packages.django.db.backends.postgresql_psycopg2',
              'myvenv.Lib.site-packages.django.db.migrations',
              'myvenv.Lib.site-packages.django.db.migrations.operations', 'myvenv.Lib.site-packages.django.apps',
              'myvenv.Lib.site-packages.django.conf', 'myvenv.Lib.site-packages.django.conf.urls',
              'myvenv.Lib.site-packages.django.conf.locale', 'myvenv.Lib.site-packages.django.conf.locale.ar',
              'myvenv.Lib.site-packages.django.conf.locale.az', 'myvenv.Lib.site-packages.django.conf.locale.bg',
              'myvenv.Lib.site-packages.django.conf.locale.bn', 'myvenv.Lib.site-packages.django.conf.locale.bs',
              'myvenv.Lib.site-packages.django.conf.locale.ca', 'myvenv.Lib.site-packages.django.conf.locale.cs',
              'myvenv.Lib.site-packages.django.conf.locale.cy', 'myvenv.Lib.site-packages.django.conf.locale.da',
              'myvenv.Lib.site-packages.django.conf.locale.de', 'myvenv.Lib.site-packages.django.conf.locale.el',
              'myvenv.Lib.site-packages.django.conf.locale.en', 'myvenv.Lib.site-packages.django.conf.locale.eo',
              'myvenv.Lib.site-packages.django.conf.locale.es', 'myvenv.Lib.site-packages.django.conf.locale.et',
              'myvenv.Lib.site-packages.django.conf.locale.eu', 'myvenv.Lib.site-packages.django.conf.locale.fa',
              'myvenv.Lib.site-packages.django.conf.locale.fi', 'myvenv.Lib.site-packages.django.conf.locale.fr',
              'myvenv.Lib.site-packages.django.conf.locale.fy', 'myvenv.Lib.site-packages.django.conf.locale.ga',
              'myvenv.Lib.site-packages.django.conf.locale.gd', 'myvenv.Lib.site-packages.django.conf.locale.gl',
              'myvenv.Lib.site-packages.django.conf.locale.he', 'myvenv.Lib.site-packages.django.conf.locale.hi',
              'myvenv.Lib.site-packages.django.conf.locale.hr', 'myvenv.Lib.site-packages.django.conf.locale.hu',
              'myvenv.Lib.site-packages.django.conf.locale.id', 'myvenv.Lib.site-packages.django.conf.locale.is',
              'myvenv.Lib.site-packages.django.conf.locale.it', 'myvenv.Lib.site-packages.django.conf.locale.ja',
              'myvenv.Lib.site-packages.django.conf.locale.ka', 'myvenv.Lib.site-packages.django.conf.locale.km',
              'myvenv.Lib.site-packages.django.conf.locale.kn', 'myvenv.Lib.site-packages.django.conf.locale.ko',
              'myvenv.Lib.site-packages.django.conf.locale.lt', 'myvenv.Lib.site-packages.django.conf.locale.lv',
              'myvenv.Lib.site-packages.django.conf.locale.mk', 'myvenv.Lib.site-packages.django.conf.locale.ml',
              'myvenv.Lib.site-packages.django.conf.locale.mn', 'myvenv.Lib.site-packages.django.conf.locale.nb',
              'myvenv.Lib.site-packages.django.conf.locale.nl', 'myvenv.Lib.site-packages.django.conf.locale.nn',
              'myvenv.Lib.site-packages.django.conf.locale.pl', 'myvenv.Lib.site-packages.django.conf.locale.pt',
              'myvenv.Lib.site-packages.django.conf.locale.ro', 'myvenv.Lib.site-packages.django.conf.locale.ru',
              'myvenv.Lib.site-packages.django.conf.locale.sk', 'myvenv.Lib.site-packages.django.conf.locale.sl',
              'myvenv.Lib.site-packages.django.conf.locale.sq', 'myvenv.Lib.site-packages.django.conf.locale.sr',
              'myvenv.Lib.site-packages.django.conf.locale.sv', 'myvenv.Lib.site-packages.django.conf.locale.ta',
              'myvenv.Lib.site-packages.django.conf.locale.te', 'myvenv.Lib.site-packages.django.conf.locale.th',
              'myvenv.Lib.site-packages.django.conf.locale.tr', 'myvenv.Lib.site-packages.django.conf.locale.uk',
              'myvenv.Lib.site-packages.django.conf.locale.vi', 'myvenv.Lib.site-packages.django.conf.locale.de_CH',
              'myvenv.Lib.site-packages.django.conf.locale.en_AU', 'myvenv.Lib.site-packages.django.conf.locale.en_GB',
              'myvenv.Lib.site-packages.django.conf.locale.es_AR', 'myvenv.Lib.site-packages.django.conf.locale.es_CO',
              'myvenv.Lib.site-packages.django.conf.locale.es_MX', 'myvenv.Lib.site-packages.django.conf.locale.es_NI',
              'myvenv.Lib.site-packages.django.conf.locale.es_PR', 'myvenv.Lib.site-packages.django.conf.locale.pt_BR',
              'myvenv.Lib.site-packages.django.conf.locale.sr_Latn',
              'myvenv.Lib.site-packages.django.conf.locale.zh_Hans',
              'myvenv.Lib.site-packages.django.conf.locale.zh_Hant', 'myvenv.Lib.site-packages.django.core',
              'myvenv.Lib.site-packages.django.core.mail', 'myvenv.Lib.site-packages.django.core.mail.backends',
              'myvenv.Lib.site-packages.django.core.cache', 'myvenv.Lib.site-packages.django.core.cache.backends',
              'myvenv.Lib.site-packages.django.core.files', 'myvenv.Lib.site-packages.django.core.checks',
              'myvenv.Lib.site-packages.django.core.checks.security',
              'myvenv.Lib.site-packages.django.core.checks.compatibility',
              'myvenv.Lib.site-packages.django.core.servers', 'myvenv.Lib.site-packages.django.core.handlers',
              'myvenv.Lib.site-packages.django.core.management', 'myvenv.Lib.site-packages.django.core.serializers',
              'myvenv.Lib.site-packages.django.http', 'myvenv.Lib.site-packages.django.test',
              'myvenv.Lib.site-packages.django.urls', 'myvenv.Lib.site-packages.django.forms',
              'myvenv.Lib.site-packages.django.utils', 'myvenv.Lib.site-packages.django.utils.translation',
              'myvenv.Lib.site-packages.django.views', 'myvenv.Lib.site-packages.django.views.generic',
              'myvenv.Lib.site-packages.django.views.decorators', 'myvenv.Lib.site-packages.django.contrib',
              'myvenv.Lib.site-packages.django.contrib.gis', 'myvenv.Lib.site-packages.django.contrib.gis.db',
              'myvenv.Lib.site-packages.django.contrib.gis.db.models',
              'myvenv.Lib.site-packages.django.contrib.gis.db.models.sql',
              'myvenv.Lib.site-packages.django.contrib.gis.db.backends',
              'myvenv.Lib.site-packages.django.contrib.gis.db.backends.base',
              'myvenv.Lib.site-packages.django.contrib.gis.db.backends.mysql',
              'myvenv.Lib.site-packages.django.contrib.gis.db.backends.oracle',
              'myvenv.Lib.site-packages.django.contrib.gis.db.backends.postgis',
              'myvenv.Lib.site-packages.django.contrib.gis.db.backends.spatialite',
              'myvenv.Lib.site-packages.django.contrib.gis.gdal',
              'myvenv.Lib.site-packages.django.contrib.gis.gdal.raster',
              'myvenv.Lib.site-packages.django.contrib.gis.gdal.prototypes',
              'myvenv.Lib.site-packages.django.contrib.gis.geos',
              'myvenv.Lib.site-packages.django.contrib.gis.geos.prototypes',
              'myvenv.Lib.site-packages.django.contrib.gis.admin', 'myvenv.Lib.site-packages.django.contrib.gis.forms',
              'myvenv.Lib.site-packages.django.contrib.gis.utils', 'myvenv.Lib.site-packages.django.contrib.gis.geoip2',
              'myvenv.Lib.site-packages.django.contrib.gis.sitemaps',
              'myvenv.Lib.site-packages.django.contrib.gis.serializers', 'myvenv.Lib.site-packages.django.contrib.auth',
              'myvenv.Lib.site-packages.django.contrib.auth.handlers',
              'myvenv.Lib.site-packages.django.contrib.auth.management',
              'myvenv.Lib.site-packages.django.contrib.auth.migrations',
              'myvenv.Lib.site-packages.django.contrib.admin', 'myvenv.Lib.site-packages.django.contrib.admin.views',
              'myvenv.Lib.site-packages.django.contrib.admin.migrations',
              'myvenv.Lib.site-packages.django.contrib.admin.templatetags',
              'myvenv.Lib.site-packages.django.contrib.sites',
              'myvenv.Lib.site-packages.django.contrib.sites.migrations',
              'myvenv.Lib.site-packages.django.contrib.humanize',
              'myvenv.Lib.site-packages.django.contrib.humanize.templatetags',
              'myvenv.Lib.site-packages.django.contrib.messages',
              'myvenv.Lib.site-packages.django.contrib.messages.storage',
              'myvenv.Lib.site-packages.django.contrib.postgres',
              'myvenv.Lib.site-packages.django.contrib.postgres.forms',
              'myvenv.Lib.site-packages.django.contrib.postgres.fields',
              'myvenv.Lib.site-packages.django.contrib.postgres.aggregates',
              'myvenv.Lib.site-packages.django.contrib.sessions',
              'myvenv.Lib.site-packages.django.contrib.sessions.backends',
              'myvenv.Lib.site-packages.django.contrib.sessions.migrations',
              'myvenv.Lib.site-packages.django.contrib.sitemaps', 'myvenv.Lib.site-packages.django.contrib.admindocs',
              'myvenv.Lib.site-packages.django.contrib.flatpages',
              'myvenv.Lib.site-packages.django.contrib.flatpages.migrations',
              'myvenv.Lib.site-packages.django.contrib.flatpages.templatetags',
              'myvenv.Lib.site-packages.django.contrib.redirects',
              'myvenv.Lib.site-packages.django.contrib.redirects.migrations',
              'myvenv.Lib.site-packages.django.contrib.staticfiles',
              'myvenv.Lib.site-packages.django.contrib.staticfiles.templatetags',
              'myvenv.Lib.site-packages.django.contrib.syndication',
              'myvenv.Lib.site-packages.django.contrib.contenttypes',
              'myvenv.Lib.site-packages.django.contrib.contenttypes.management',
              'myvenv.Lib.site-packages.django.contrib.contenttypes.migrations',
              'myvenv.Lib.site-packages.django.dispatch', 'myvenv.Lib.site-packages.django.template',
              'myvenv.Lib.site-packages.django.template.loaders', 'myvenv.Lib.site-packages.django.template.backends',
              'myvenv.Lib.site-packages.django.middleware', 'myvenv.Lib.site-packages.django.templatetags',
              'myvenv.Lib.site-packages.sqlparse', 'myvenv.Lib.site-packages.sqlparse.engine',
              'myvenv.Lib.site-packages.sqlparse.filters', 'myvenv.Lib.site-packages.setuptools',
              'myvenv.Lib.site-packages.setuptools.extern', 'myvenv.Lib.site-packages.setuptools.command',
              'myvenv.Lib.site-packages.pkg_resources', 'myvenv.Lib.site-packages.pkg_resources.extern',
              'myvenv.Lib.site-packages.pkg_resources._vendor',
              'myvenv.Lib.site-packages.pkg_resources._vendor.packaging'],
    url='',
    license='',
    author='james',
    author_email='',
    description=''
)
